import { NextPage } from 'next';
import Head from 'next/head'

const Home : NextPage = () =>  {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1 className='text-3xl font-bold underline'>Damilola</h1>
      </main>
    </>
  );
}


export default Home